#include<raylib.h>
#include<stdio.h>
#include<stdbool.h>
#include<stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include<sys/stat.h>
#include<stdlib.h>
#include<string.h>
#include<errno.h>
#include<pthread.h>
#include<time.h>

#include "../emulator/chip8.h"

extern uint8_t V[16];
extern uint16_t I;
extern uint16_t PC;
extern uint8_t STACKPOINTER;
extern volatile uint8_t DELAYTIMER;
extern volatile uint8_t SOUNDTIMER;
extern volatile bool KEYS[16];
extern bool DISPLAY[32][64];
extern uint8_t RAM[4096];


//lock used to ensure mutual exclusion to the delaytimer and soundtimer variables
//it's needed in the case of the timers because there is more than one thread that can write to them
pthread_mutex_t timerlock=PTHREAD_MUTEX_INITIALIZER;

volatile bool advance_once=false; //set true by the UI thread and to false by the timer thread, signals to advace the timers only once 


// function run by the thread that updates the timers
void * timerthread(void * param);


//global variables used to comunicate between the UI thread and the worker thread
volatile unsigned int instructions_per_second=700; //desired amount of instructions per second to execute, set by the UI thread
volatile bool paused=true; //set by the UI thread and read by the other threads, signals if execution and timers are on pause
volatile bool execute_once=false; //set true by the UI thread and to false by the worker thread, signals to execute one instruction then stop 

volatile ErrorCode_t errorcode=NO_ERROR; //set by the worker thread, signals errors encountered during execution

// function run by the worker thread that executes instructions independently from the ui thread
void * workerthread(void * param);


// 2D texture used to represent the contents of the RAM, a texture is used to make use of bilinear filtering
Texture2D ramtexture;


// music stream to play CHIP8's buzzer
Music beep;
const char beep_filename[]="sounds/square_294Hz_5s.wav";
const float beep_volume=0.8f;


void load_rom(char *filename);
void draw_display();
void draw_memory();
void draw_keypad();
void draw_button(int x,int y,const char * text,bool pressed);
void draw_registers();
void draw_error_code();

int main(int argc, char **argv){
    if(argc<2){
        printf("must include a rom file to load into memory\n");
        return 1;
    }

    load_rom(argv[1]);


    printf("initializing registers...\n");
    for(int i=0;i<16;i++) V[i]=0;
    I=0;
    PC=0x200;
    STACKPOINTER=0;
    DELAYTIMER=0;
    SOUNDTIMER=0;
    for(int i=0;i<16;i++) KEYS[i]=false;
    CHIP8_display_clear();
    printf("done\n\n");
    

    //initialize audio device and retrieve the audio file
    InitAudioDevice();
    beep = LoadMusicStream(beep_filename);
    beep.looping=true;
    SetMusicVolume(beep,beep_volume);
    PlayMusicStream(beep);
    PauseMusicStream(beep); 

    //start the timer thread
    pthread_t timerth;
    pthread_attr_t timerattr;
    pthread_attr_init(&timerattr);
    pthread_attr_setdetachstate(&timerattr,PTHREAD_CREATE_DETACHED);
    pthread_create(&timerth,&timerattr,timerthread,(void*)0);
    pthread_attr_destroy(&timerattr);

    //start the worker thread
    pthread_t workerth;
    pthread_attr_t workerattr;
    pthread_attr_init(&workerattr);
    pthread_attr_setdetachstate(&workerattr,PTHREAD_CREATE_DETACHED);
    pthread_create(&workerth,&workerattr,workerthread,(void*)0);
    pthread_attr_destroy(&workerattr);


    //main thread goes on to create the window and drawing the UI
    InitWindow(850,400,"Chipppppppp Control Panel");
    SetWindowState(FLAG_WINDOW_RESIZABLE | FLAG_WINDOW_MAXIMIZED);
    SetTargetFPS(60);


    // create the texture of the RAM diagram, starting from an image generated by code
    Color *pixels=malloc(4096*sizeof(Color));
    memset(pixels,0,4096*sizeof(Color));
    Image ramimage={
        .data=pixels,
        .width=4096,
        .height=1,
        .format=PIXELFORMAT_UNCOMPRESSED_R8G8B8A8,
        .mipmaps=1
    };
    // create and load the texture
    ramtexture=LoadTextureFromImage(ramimage);
    UnloadImage(ramimage);
    // i don't know what bilinear filtering is, but it seems to blend the colors well enough when the texture is squished to less than 4096 pixels across
    SetTextureFilter(ramtexture,TEXTURE_FILTER_BILINEAR);


    while(!WindowShouldClose()){
        //UPDATING

        //keep the music going
        UpdateMusicStream(beep);

        // update global variables based on user input
        KEYS[0]=IsKeyDown(KEY_X);
        KEYS[1]=IsKeyDown(KEY_ONE);
        KEYS[2]=IsKeyDown(KEY_TWO);
        KEYS[3]=IsKeyDown(KEY_THREE);
        KEYS[4]=IsKeyDown(KEY_Q);
        KEYS[5]=IsKeyDown(KEY_W);
        KEYS[6]=IsKeyDown(KEY_E);
        KEYS[7]=IsKeyDown(KEY_A);
        KEYS[8]=IsKeyDown(KEY_S);
        KEYS[9]=IsKeyDown(KEY_D);
        KEYS[A]=IsKeyDown(KEY_Z);
        KEYS[B]=IsKeyDown(KEY_C);
        KEYS[C]=IsKeyDown(KEY_FOUR);
        KEYS[D]=IsKeyDown(KEY_R);
        KEYS[E]=IsKeyDown(KEY_F);
        KEYS[F]=IsKeyDown(KEY_V);


        if(IsKeyPressed(KEY_SPACE)){
            paused=!paused;
        }

        if(paused && IsMouseButtonPressed(MOUSE_BUTTON_LEFT)){
            execute_once=true;
        }

        if(paused && IsMouseButtonPressed(MOUSE_BUTTON_RIGHT)){
            advance_once=true;
        }

        // update instructions_per_second, 1 billion is an optimistic maximum
        if(IsKeyPressed(KEY_KP_ADD) || IsKeyPressedRepeat(KEY_KP_ADD)){
            instructions_per_second+=instructions_per_second/20;
            if(instructions_per_second>1000000000) instructions_per_second=1000000000;
        }

        if(IsKeyPressed(KEY_KP_SUBTRACT) || IsKeyPressedRepeat(KEY_KP_SUBTRACT)){
            instructions_per_second-=instructions_per_second/20;
            if(instructions_per_second<20) instructions_per_second=20;
        }


        // DRAWING
        BeginDrawing();

        ClearBackground(RAYWHITE);

        draw_display();
        draw_keypad();
        draw_registers();
        draw_memory();
        draw_error_code();
        if(paused && errorcode==NO_ERROR) DrawText("PAUSED",710,10,60,RED);

        EndDrawing();
    }

    //cleanup
    UnloadTexture(ramtexture);
    CloseWindow();

    pthread_cancel(timerth);
    pthread_mutex_destroy(&timerlock);

    //only cancel the worker thread if it did not run into an error, because then it would already have terminated
    if(errorcode==NO_ERROR) pthread_cancel(workerth);

    UnloadMusicStream(beep);
    CloseAudioDevice();
}



void * workerthread(void * param){
    // set this thread to be able to be cancelled
    pthread_setcancelstate(PTHREAD_CANCEL_ENABLE,NULL);
    pthread_setcanceltype(PTHREAD_CANCEL_DEFERRED,NULL);


    
    //continue an infinite loop of executing, only stopping if we encounter an error
    while(errorcode==NO_ERROR){
        //store execute_once in a local variable to make sure it's the same value both times it gets read inside the if statement
        bool eo=execute_once;
        if(!paused || eo){
            //acquire the locks on the timers and execte an instruction
            pthread_mutex_lock(&timerlock);
            errorcode=CHIP8_next_instruction();
            pthread_mutex_unlock(&timerlock);

            //set the flag to false to make sure we execute only once for every time UI thread sets it to true
            if(eo) execute_once=false;
        }

        // wait an amount of time determined by the desired instructions per second
        struct timespec ts={.tv_sec=0,.tv_nsec=1000000000/(instructions_per_second)};
        nanosleep(&ts,NULL); //nanosleep is overkill but we need a cancellation point somewhere to be able to cancel the thread
    }


    //if we exited the loop it means we encountered an error
    // so we decrease PC so it points to the instruction that cause the error
    PC=PC-2;
    return NULL;
}


void * timerthread(void * param){
    //set this thread to be able to be cancelled
    pthread_setcancelstate(PTHREAD_CANCEL_ENABLE,NULL);
    pthread_setcanceltype(PTHREAD_CANCEL_DEFERRED,NULL);

    // enter infinite loop of decreasing the timers at a frequency of 60hz
    while(1){
        bool ao=advance_once;
        if(!paused || ao){
            pthread_mutex_lock(&timerlock);
            CHIP8_advance_timers();

            if(SOUNDTIMER==0){
                PauseMusicStream(beep);
            }else{
                ResumeMusicStream(beep);
            }

            pthread_mutex_unlock(&timerlock);

            if(ao) advance_once=false;
        }else{
            PauseMusicStream(beep);
        }
        // wait one 60th of a second
        struct timespec ts={.tv_sec=0,.tv_nsec=16666666};
        nanosleep(&ts,NULL); //nanosleep is overkill but we need a cancellation point somewhere to be able to cancel the thread
    }
}




void load_rom(char *filename){
    int fd=open(filename,O_RDONLY);

    if(fd<0){
        puts(strerror(errno));
        printf("\nfailed to open rom file %s\n",filename);
        exit(2);
    }

    struct stat stats;
    if(stat(filename,&stats)==-1){
        puts(strerror(errno));
        printf("\nfailed to get stats for %s\n",filename);
        exit(3);
    }

    if(stats.st_size > 3854){
        printf("rom file %s is too big to fit in ram\n",filename);
        exit(4);
    }

    printf("reading %ld bytes from ROM file %s and loading them into RAM...\n",stats.st_size,filename);

    uint8_t *rom_bytes=malloc(stats.st_size);
    
    if(read(fd,rom_bytes,stats.st_size)==-1){
        puts(strerror(errno));
        printf("\nfailed to read %ld bytes from %s with fd=%d\n",stats.st_size,filename,fd);
        exit(5);
    }

    for(int i=0;i<stats.st_size;i++){
        RAM[0x200+i]=rom_bytes[i];
    }
    printf("sucessfully loaded program data into RAM\n");

    free(rom_bytes);
    close(fd);
}


// function that draws CHIP8's display to screen
// definitions for the location of the display and how big it is
// display width and height are determined by pixel width and height
#define DISPLAY_BASE_X 225
#define DISPLAY_BASE_Y 100
#define PIXEL_WIDTH 20
#define PIXEL_HEIGHT 20
#define PIXEL_COLOR_ON WHITE
#define PIXEL_COLOR_OFF BLACK
void draw_display(){
    Rectangle pixel;
    pixel.x=DISPLAY_BASE_X;
    pixel.y=DISPLAY_BASE_Y;
    pixel.width=PIXEL_WIDTH;
    pixel.height=PIXEL_HEIGHT;

    for(int i=0;i<32;i++){
        pixel.x=DISPLAY_BASE_X;
        for(int j=0;j<64;j++){
            Color c=DISPLAY[i][j] ? PIXEL_COLOR_ON : PIXEL_COLOR_OFF;
            DrawRectangleRec(pixel,c);
            pixel.x+=PIXEL_WIDTH;
        }
        pixel.y+=PIXEL_HEIGHT;
    }
}


// function that drawss the diagram of the ram memory
// definitions for the location of the diagram and how big it is
#define MEM_BASE_X 100
#define MEM_BASE_Y 880
#define MEM_WIDTH 1600
#define MEM_HEIGHT 100
#define MEM_SPACING 8
#define MEM_TITLE_TEXT_SIZE 20
#define MEM_ICONS_TEXT_SIZE 14
void draw_memory(){
    //draw the outline around the ram diagram
    DrawRectangle(MEM_BASE_X-MEM_SPACING,MEM_BASE_Y-7*MEM_SPACING,MEM_WIDTH+2*MEM_SPACING,MEM_HEIGHT+9*MEM_SPACING,GRAY);

    //draw the title at the top
    DrawText("Memory:",MEM_BASE_X+MEM_SPACING/2,MEM_BASE_Y-6*MEM_SPACING,MEM_TITLE_TEXT_SIZE,BLACK);

    //draw the little icon that points to the address in I
    const int iiconpos=(((float)I)/4096.0f)*MEM_WIDTH; 
    DrawText("I",MEM_BASE_X+iiconpos,MEM_BASE_Y-3*MEM_SPACING,MEM_ICONS_TEXT_SIZE,BLACK);

    //draw the little icon that points to the address in PC
    const int pciconpos=(((float)PC)/4096.0f)*MEM_WIDTH; 
    DrawText("PC",MEM_BASE_X+pciconpos,MEM_BASE_Y-3*MEM_SPACING,MEM_ICONS_TEXT_SIZE,BLACK);

    //draw the little address icons on the bottom
    DrawText("0x000",MEM_BASE_X,MEM_BASE_Y+MEM_HEIGHT,MEM_ICONS_TEXT_SIZE,BLACK);
    DrawText("0xFFF",MEM_BASE_X+MEM_WIDTH-3*MEM_ICONS_TEXT_SIZE,MEM_BASE_Y+MEM_HEIGHT,MEM_ICONS_TEXT_SIZE,BLACK);
    

    //make the pixels of the texture
    Color pixels[4096];
    for(int i=0;i<4096;i++){
        pixels[i]=(Color){RAM[i],RAM[i],RAM[i],255};
    }

    //update the texture loaded in vram
    UpdateTexture(ramtexture,pixels);

    // draw the texture in the defined position and size, the filtering somehow blends the colors
    DrawTexturePro(ramtexture,(Rectangle){0,0,4096,1},(Rectangle){MEM_BASE_X,MEM_BASE_Y,MEM_WIDTH,MEM_HEIGHT},(Vector2){0,0},0.0f,WHITE);
}


// function that draws CHIP8's 16 keys as a square of 16 squares
// definition for the location of the keypad and its size and color
#define KEYPAD_BASE_X 20
#define KEYPAD_BASE_Y 100
#define KEYPAD_COLOR GRAY
#define KEY_SIZE 45
#define KEY_SPACING 3
#define KEY_COLOR_PRESSED RED
#define KEY_COLOR_UNPRESSED BLACK
#define KEY_COLOR_BACKGROUND LIGHTGRAY
#define KEY_TEXT_SIZE 20
void draw_keypad(){
    DrawText("Keypad:",KEYPAD_BASE_X,KEYPAD_BASE_Y-KEY_TEXT_SIZE,KEY_TEXT_SIZE,BLACK);

    //draw outline of the keypad
    DrawRectangle(KEYPAD_BASE_X,KEYPAD_BASE_Y,KEY_SIZE*4+KEY_SPACING*5,KEY_SIZE*4+KEY_SPACING*5,KEYPAD_COLOR);

    //draw the keys 1-9 in a 3*3 square
    for(int i=0;i<9;i++){
        draw_button(i%3,i/3,TextFormat("%d",1+i),KEYS[1+i]);
    }
    //draw the keus C-F on the rightmost column
    for(int i=0;i<4;i++){
        draw_button(3,i,TextFormat("%X",C+i),KEYS[C+i]);
    }
    //draw A,0,B on the bottom
    draw_button(0,3,"A",KEYS[A]);
    draw_button(1,3,"0",KEYS[0]);
    draw_button(2,3,"B",KEYS[B]);
}

void draw_button(int x,int y,const char * text,bool pressed){
    x=KEYPAD_BASE_X+KEY_SPACING+x*(KEY_SPACING+KEY_SIZE);
    y=KEYPAD_BASE_Y+KEY_SPACING+y*(KEY_SPACING+KEY_SIZE);

    DrawRectangle(x,y,KEY_SIZE,KEY_SIZE,KEY_COLOR_BACKGROUND);

    Color c=pressed ? KEY_COLOR_PRESSED : KEY_COLOR_UNPRESSED;
    
    DrawText(text,x+KEY_SIZE/2-KEY_TEXT_SIZE/2+3,y+KEY_SIZE/2-KEY_TEXT_SIZE/2,KEY_TEXT_SIZE,c);
}


// function that draws the values of the registers and timers and whatnot
#define REGISTERS_BASE_X 1525
#define REGISTERS_BASE_Y 100
#define REGISTERS_TEXT_COLOR BLACK
#define REGISTERS_TEXT_SIZE 20 
void draw_registers(){
    const char *text=TextFormat("");

    text=TextFormat("%sCurrent Instruction: 0x%02X%02X\nTarget IPS: %d",text,RAM[PC],RAM[PC+1],instructions_per_second);

    text=TextFormat("%s\n\nAddresses:\nPC=0x%03X\nI=0x%03X\nSP=%d",text,PC,I,STACKPOINTER);

    text=TextFormat("%s\n\nRegisters:",text);
    for(int i=0;i<16;i++){text=TextFormat("%s\nV%X=%d",text,i,V[i]);}

    text=TextFormat("%s\n\nTimers:\nDelay timer=%d\nSound timer=%d",text,DELAYTIMER,SOUNDTIMER);

    DrawText(text,REGISTERS_BASE_X,REGISTERS_BASE_Y,REGISTERS_TEXT_SIZE,REGISTERS_TEXT_COLOR);
}


//function that displays errors if they occur
#define ERRORCODE_BASE_X 225
#define ERRORCODE_BASE_Y 30
#define ERRORCODE_TEXT_SIZE 40
#define ERRORCODE_TEXT_COLOR RED
void draw_error_code(){
    if(errorcode==NO_ERROR) return;


    char text[27];

    switch (errorcode){
        case INVALID_INSTRUCTION:
        sprintf(text,"ERROR: INVALID_INSTRUCTION");
        break;
        case INVALID_ADDRESS_PC:
        sprintf(text,"ERROR: INVALID_ADDRESS_PC");
        break;
        case RESERVED_ADDRESS_PC:
        sprintf(text,"ERROR: RESERVED_ADDRESS_PC");
        break;
        case INVALID_ADDRESS_I:
        sprintf(text,"ERROR: INVALID_ADDRESS_I");
        break;
        case RESERVED_ADDRESS_I:
        sprintf(text,"ERROR: RESERVED_ADDRESS_I");
        break;
        case STACK_OVERFLOW:
        sprintf(text,"ERROR: STACK_OVERFLOW");
        break;
        case STACK_UNDERFLOW:
        sprintf(text,"ERROR: STACK_UNDERFLOW");
        break;
        case INVALID_BUTTON:
        sprintf(text,"ERROR: INVALID_BUTTON");
        break;
        case INVALID_SPRITE:
        sprintf(text,"ERROR: INVALID_SPRITE");
        break;
        default:
        break;
    }


    DrawText(text,ERRORCODE_BASE_X,ERRORCODE_BASE_Y,ERRORCODE_TEXT_SIZE,ERRORCODE_TEXT_COLOR);
}